import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRef } from 'react';
import styles from '../styles/Home.module.css';
import Icicles from 'icicles';
import Box from '../components/Box';

const Home: NextPage = () => {
	const boxRef = useRef<HTMLDivElement>(null);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Box backgroundColor='red' />
		</div>
	);
};

export default Home;
